# Generated by Django 5.1.3 on 2024-11-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True, verbose_name='Kursning nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ursning tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kurs yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Kurs oxirgi tahrirlangan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Talabaning ismi')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Talabaning email manzili')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatdan o‘tgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.course', verbose_name='Course modeliga bog’lanadi')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Izohning matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Izoh qoldirilgan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.course', verbose_name='Izoh qaysi kursga tegishli ekanligi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.student', verbose_name='Izohni qaysi talaba yozgani')),
            ],
        ),
    ]
